// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhk6j6ofxvPcg-NElG0J9UbZSE6R8fsHA',
    appId: '1:54982514977:web:d57a2587c9fd4ec0260660',
    messagingSenderId: '54982514977',
    projectId: 'sahayak-8cfeb',
    authDomain: 'sahayak-8cfeb.firebaseapp.com',
    storageBucket: 'sahayak-8cfeb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdfxsLJpoW2_H0iz1_ePTtG9QrDfesMok',
    appId: '1:54982514977:android:bc60293b3379c6c2260660',
    messagingSenderId: '54982514977',
    projectId: 'sahayak-8cfeb',
    storageBucket: 'sahayak-8cfeb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDazUTjIQ68F4tcvef8Jrvs5ParkcSG5pc',
    appId: '1:54982514977:ios:0f648e4e33a4f998260660',
    messagingSenderId: '54982514977',
    projectId: 'sahayak-8cfeb',
    storageBucket: 'sahayak-8cfeb.firebasestorage.app',
    iosBundleId: 'com.example.sahayak',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDazUTjIQ68F4tcvef8Jrvs5ParkcSG5pc',
    appId: '1:54982514977:ios:0f648e4e33a4f998260660',
    messagingSenderId: '54982514977',
    projectId: 'sahayak-8cfeb',
    storageBucket: 'sahayak-8cfeb.firebasestorage.app',
    iosBundleId: 'com.example.sahayak',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhk6j6ofxvPcg-NElG0J9UbZSE6R8fsHA',
    appId: '1:54982514977:web:5a93849d7cdfb4f7260660',
    messagingSenderId: '54982514977',
    projectId: 'sahayak-8cfeb',
    authDomain: 'sahayak-8cfeb.firebaseapp.com',
    storageBucket: 'sahayak-8cfeb.firebasestorage.app',
  );
}
